### ISSUE TITLE
Configuration Load is not Awaited

### ISSUE THREAD

**Issue by gotdibbs** [forcedotcom/SalesforceMobileSDK-Windows#149]
We're seeing an app crash when trying to update to the latest code in the unstable branch for the Mobile SDK for Windows. 

Since line 66 of the [`SalesforceApplication`](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/blob/unstable/SalesforceSDK/Universal/App/SalesforceApplication.cs#L66) class is not awaited, the app will crash on trying to access the configuration before it has been loaded. The crash specifically happens on line 99 of [`AccountPage.xaml.cs`](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/blob/unstable/SalesforceSDK/Universal/Pages/AccountPage.xaml.cs#L99) when `config.ApplicationTitle` is accessed.

**Comment by kchitalia** [comment]
@smcnulty-sfdc Can you please provide your input here.

**Comment by kchitalia** [comment]
@gotdibbs This will be fixed in our next release.

**Comment by helenren** [comment]
Close this issue since we do not see this crash issue anymore on our latest bits on unstable. The issue has been fixed
