### ISSUE TITLE
Illegible Error Dialog Presented When User Selects "Deny" on Login

### ISSUE THREAD

**Issue by gotdibbs** [forcedotcom/SalesforceMobileSDK-Windows#153]
When going through the login flow, if a user selects "Deny" instead of "Allow" on the permissions page displayed in the `WebAuthenticationBroker`, they are presented with a too small dialog that has the exact details of the error, but in a hard to read format.

Since the exact detail of the error is provided in the response query string, would it be possible to instead treat the denied permissions selection the same way as if the user cancelled the login?

For context, this error message is displayed on [Line 296 of Universal\AccountPage.xaml.cs](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/blob/unstable/SalesforceSDK/Universal/Pages/AccountPage.xaml.cs#L296).

**Comment by huminzhi** [comment]
@gotdibbs sorry to follow up late on this, wondering if you already solved this issue?

**Comment by gotdibbs** [comment]
@huminzhi We've moved on from this project (it was a demo app) and I no longer have access to an organization to test this flow in, so I cannot confirm if this is resolved. That said, it does appear the logic in that page has changed, so it may be. Again, the issue was that it was displaying an unreadable error when selecting "Deny" during the auth flow. If there is a more user friendly error that presents itself, or a way for the consumer of this SDK to handle this error directly, I would consider this resolved.

**Comment by kchitalia** [comment]
@huminzhi @gotdibbs The control that displays the error message is not controlled by the SDK team. In any case, from the changes that I have seen recently, the error message is legible. I would say we can consider this resolved.
