### ISSUE TITLE
ProfileId field in Account class

### ISSUE THREAD

**Issue by eklimanov** [forcedotcom/SalesforceMobileSDK-Windows#224]
Why class Account does not have the field ProfileId? A lot of logic uses this field for access control. E.g. CustomSettings has access by ProfileId.

**Comment by helenren** [comment]
@eklimanov could you please elaborate your request, like what kind of information you expect to be included in that Profield, and code logic that you want to use it, etc. This will help us to understand your request better. Thanks

**Comment by eklimanov** [comment]
Ok. 
Each User in SF has a profile like **System Administrator**, **Standard User** and so one. At User record this relationship is introducing over field **ProfileId**. This field has type **Id** as alias for **text(18)** type. In standard Apex class **Userinfo** has method **getProfileId()** which return this information. I would like see this information in class **Account** from Salesforce Mobile SDK. 
I can describe for you some usercase why we need this information in SDK. We have been developing mobile application for IOS devices during last three year. And last 2 months we started to develop mobile application for Windows 10. In Salesforce our decision has several hierarcical custom settings where we store settings for mobile application by access **UserId**, **ProfileId** and Default (**OrganisationId**). Each of this custom settings has field SetupOwnerId which link with User, Profile or Organisation. When we want give our Clients opportunity to work with not all accessible Objects from Salesforce but only with important objects we are creating record in custom settings for they **UserProfile** and we are storing names of these Objects in this record. On mobile application we read all custom settings but if we will have ProfileId we can read only custom settings for current authenticated user. Then we will can flexibly adjust our app. So our application will be still very light weigth and user frendly. Thanks.

**Comment by helenren** [comment]
Thanks @eklimanov , it is on our backlog, will try to address it as soon as possible.
