### ISSUE TITLE
Merge the unstable branch into the stable branch

### ISSUE THREAD

**Issue by sanjeevdwivedi** [forcedotcom/SalesforceMobileSDK-Windows#235]
Given the SDK works at this point of time, can we merge the changes back. Especially, the README would help new folks get started @kchitalia @huminzhi The current instructions confuse folks.

**Comment by urthakkar** [comment]
We will be following our release process and in the mean time please use the unstable (which is really development).

**Comment by bhariharan** [comment]
`unstable` is our development branch. It'll get merged to `master` when we release.

**Comment by sanjeevdwivedi** [comment]
@bhariharan @urthakkar @kchitalia Is it possible to keep this issue open till the release. Also, when will the release happen? At the very least, the README on the master branch needs to be updated so that anyone coming to the repo knows that they need to go to the unstable branch. Right now, anyone coming to the repo will try the old steps and will not even know that they need to go to the unstable branch.

**Comment by khawkins** [comment]
If the master branch is far enough out of date as to be unusable, perhaps we should just set `unstable` as the default branch of the repo for the time being, so people end up there automatically.

**Comment by bhariharan** [comment]
@sanjeevdwivedi The issues forum is for known bugs/issues with this product that need to be fixed.

**Comment by sanjeevdwivedi** [comment]
@khawkins @bhariharan @urthakkar @kchitalia 

The approach of simply making the unstable branch as the default branch seems like a reasonable stopgap while the release process is followed through. Also, what is the timeline around release?
