### ISSUE TITLE
Salesforce.SDK.Universal v 4.2.0 nuget package is not being installed on UWP project

### ISSUE THREAD

**Issue by SravanthiKare1** [forcedotcom/SalesforceMobileSDK-Windows#239]
Salesforce.SDK.Universal v 4.2.0 nuget package is not being installed on UWP project.
But the dll taken from git source code has no issues. Can you please update nuget packages with the latest code provided in GitHub

**Comment by helenren** [comment]
@SravanthiKare1 so other sdk packages are installed, except for universal one? Could you pls give me more detail steps that make you hit that issue?

Just had a try locally, all sdk packages defined in the package.json file are installed successfully for me. I tried is to create a UWP project via createapp.ps1 from unstable branch.

**Comment by SravanthiKare1** [comment]
All other SDKs(Core, SmartSync, SmartStore) are getting installed except for Salesforce.SDK.Universal. 

**Error**:
Restoring packages for ..\project.json...
Salesforce.SDK.Universal 4.2.0 provides a compile-time reference assembly for Salesforce.SDK.Universal on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Salesforce.SDK.Universal 4.2.0 provides a compile-time reference assembly for Salesforce.SDK.Universal on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).

**Other Details:**
Approach1 - If we try to install from nuget package manager, it is throwing above error.
Approach2 - If we add package in project.json, it is getting installed but throwing same error when we build the project.

**Comment by helenren** [comment]
@SravanthiKare1, what't the platform do you choose when doing build? x64? Please try x86 or ARM. We only supply x86 and ARM build for it. Do you need x64 version specifically? Thanks.

**Comment by helenren** [comment]
@SravanthiKare1, do you still have the issue? If not, I will go ahead close this issue. Thanks
