### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by BigBadChicago** [forcedotcom/SalesforceMobileSDK-Windows#89]
I've installed all of the extensions on VS2013 Ultimate Update 4 and installed the zip file in the correct directory.  When I try to create a new project, the project creation fails, and I get an error that states "Error: this template attempted to load component assembly 'TemplateWizard, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=69245b93ade9431a'."  I have attempted it with .NET Framework 4, .NET Framework 4.5 and .NET Framework 4.5.1.  

I think it may have something to the optional settings around the Connected App and OAuth scopes.  I've attached an image of the error.

![templatewizarderror](https://cloud.githubusercontent.com/assets/120721/7434322/a8905546-efff-11e4-8c44-faf90a0940bb.png)

**Comment by kchitalia** [comment]
Hi Jonathan,

Can you try running Visual Studio as an Administrator.

Sent from my iPhone

On May 1, 2015, at 10:43 AM, Jonathan Baltz <notifications@github.com>
wrote:

I've installed all of the extensions on VS2013 Ultimate Update 4 and
installed the zip file in the correct directory. When I try to create a new
project, the project creation fails, and I get an error that states "Error:
this template attempted to load component assembly 'TemplateWizard,
Version=1.0.0.0, Culture=Neutral, PublicKeyToken=69245b93ade9431a'." I have
attempted it with .NET Framework 4, .NET Framework 4.5 and .NET Framework
4.5.1.

I think it may have something to the optional settings around the Connected
App and OAuth scopes. I've attached an image of the error.

[image: templatewizarderror]
<https://cloud.githubusercontent.com/assets/120721/7434322/a8905546-efff-11e4-8c44-faf90a0940bb.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/SalesforceMobileSDK-Windows/issues/89>.

**Comment by BigBadChicago** [comment]
Still a no go.

**Comment by kchitalia** [comment]
If you have the SDK git repo cloned, open up the git repo in Visual Studio, try cleaning and building the template wizard project. The template has to be registered with VS.

**Comment by kchitalia** [comment]
Did the previous suggestion resolve your issue?

**Comment by BigBadChicago** [comment]
Sorry, but when I opened up the project, it said that I had 3200+ errors.  Someone suggested that I uninstall and reinstall VS13 Ultimate, which I did, but I still got the errors for the project and the template.

**Comment by BigBadChicago** [comment]
FYI: Another SFDC developer is having the same issue and mentioned it on Twitter.  https://twitter.com/codefriar/status/598192954994470912

**Comment by noeticpenguin** [comment]
How do I go about registering the template?

**Comment by smcnulty-sfdc** [comment]
The easiest way is to clone the repo and build the "TemplateWizard" project that comes with it.  This will generate the template and automatically place it in the correct place for you. You will need to launch visual studio with admin rights so that it can run scripts that are associated with that template (mainly powershell, used to combine and build the template from scratch).  The scripts that are run are all included with the SDK, you can look at the code to see the process.

You can also see the line used to register the dll on the post-build action for TemplateWizard; basically it uses gacutil to register the dll, so that the template can have a custom UI as part of the process of creating a project using the template so you can preset some variables.

**Comment by noeticpenguin** [comment]
@smcnulty-sfdc Thanks for this. Can I suggest editing the instructions on the blog post to replace the whole "copy the file" to what you just wrote.

**Comment by kchitalia** [comment]
Closing out this issue as the suggestion made by @smcnulty-sfdc resolves it.

**Comment by singhprateek2695** [comment]
I'm getting the same error again in visual studio 17 . Already tried everything stating above , can anyone tell me the reason as well as permanent solution for this.
![image](https://user-images.githubusercontent.com/24417532/39109395-646c4d80-46ea-11e8-9206-377c521b1355.png)

**Comment by singhprateek2695** [comment]
@BigBadChicago , can you help me with it if you were able to resolve the issue.
